controller:
  kind: Deployment
  replicaCount: 1
  service:
    type: NodePort
    nodePorts:
      http: 30080
  resources:
    requests:
      cpu: "100m"
      memory: "128Mi"
    limits:
      cpu: "500m"
      memory: "256Mi"